### ISSUE TITLE
Rules object has extra id field

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libcalico#103]
Rules are written with an ID field that doesn't appear in http://docs.projectcalico.org/en/latest/etcd-data-model.html or https://github.com/projectcalico/calico-containers/blob/master/docs/etcdStructure.md

I think it comes from this line https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/datastore_datatypes.py#L38

**Comment by robbrockbank** [comment]
Once we have a new release of calicoctl which does not expect this field - please fix up libcalico-go and calicocni-go to not expect this.

**Comment by tomdee** [comment]
Just FTR, the only thing expecting this in calicocni-go is a test - it will be easy to spot and remove _after_ libcalico-go is updated.

**Comment by robbrockbank** [comment]
Fixed in #132, and will be available in the next release of libcalico (should be today)
