### ISSUE TITLE
hostname must not contain `_` ?

### ISSUE THREAD

**Issue by tonicmuroq** [projectcalico/libcalico#104]
from [here](https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/util.py#L225) I found that when validating hostname, no `'_'` is allowed. But if I use some CI tools like gitlab-ci, when running in docker containers, the host name of the linked container would be `'hub.docker.com__service__etcd'` if the image is `'hub.docker.com/service/etcd'`. Could this be changed?

**Comment by tomdee** [comment]
Tricky. Hostnames shouldn't have underscores in them (http://www.ietf.org/rfc/rfc1034.txt) But maybe we can relax this restriction. @tonicbupt would you be able to submit a PR?

**Comment by tomdee** [comment]
See also https://github.com/docker/docker/issues/22057 and https://github.com/docker/docker/issues/20371

**Comment by tonicmuroq** [comment]
@tomdee submit #129 , the only change is that I add `'_'` in the regexp ...

**Comment by robbrockbank** [comment]
This will be in the next release of calicoctl - which I'm hoping to get out today, or Monday at the latest.
