### ISSUE TITLE
Specifying etcd endpoints doesn't work with fqdns

### ISSUE THREAD

**Issue by hanikesn** [projectcalico/libcalico#107]
I'm calling calicoctl with:

```
ETCD_ENDPOINTS=https://1.calico.etcd.local.:2381,https://2.calico.etcd.local.:2381,https://3.calico.etcd.local.:2381
```

But it aborts with:

```
Invalid ETCD_ENDPOINTS. Address must take the form <address>:<port>. Value
provided is '1.calico.etcd.local.:2381'
```

It should be possible to use fully qualified domain names.

**Comment by tomdee** [comment]
@hanikesn How important is it for you to use a fully qualified domain name here? 

PRs are always welcome - here's the line that would need fixing https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/util.py#L412

**Comment by hanikesn** [comment]
As the workaround is pretty simple I'd give it pretty low priority and just close it.

**Comment by caseydavenport** [comment]
This is fixed now.
