### ISSUE TITLE
Could path prefix be configurable ?

### ISSUE THREAD

**Issue by depay** [projectcalico/libcalico#115]
currently we got etcd structure like

```
+--calico  # root namespace
   |
   |--v1
   |--ipam
   |--bgp
   |--felix
   |--libnetwork
```

but i wanna run different networks with calico, using the same etcd server, which might be

```
+--<prefix>  # root namespace
   |
   |--calico
      |
      |--v1
      |--ipam
      |--bgp
      |--felix
      |--libnetwork
```

i found path of `v1`/`ipam`/`bgp` is defined in libcalico, path of `libnetwork` defined in libnetwork-plugin, and path of `felix` defined in another place... and i found it's hard to set a same prefix via env or else..

**Comment by fasaxc** [comment]
@depay why can't you share an etcd, what do you mean by "different networks"?  Calico's model is to use a flat layer 3 network so I'm not really sure what you mean.

**Comment by depay** [comment]
@fasaxc  thanks for reply...

e.g. i deploy my network on server s1/s2/s3, and my teammate deploys his network on server s4/s5/s6. We use a shared etcd cluster, but we wanna use it isolatedly for some reason.. as the docker arg `--cluster-store=etcd://<etcd-server>/<etcd-path-prefix>`, or many zookeeper client did.

when etcd cluster works as a shared service, simply using it's root directory instead of putting things in a subdirectory is a little chaos..

**Comment by fasaxc** [comment]
I'd recommend using an isolated etcd cluster for each Calico set-up.  If you're doing development work, then it's trivial to start a one-node cluster.  If you're in production, you shouldn't be sharing your etcd because it invalidates our scale and validation testing.

**Comment by depay** [comment]
I know that, but what we're doing now is using calico under a same router with static routing between real routers. And there may be not so many servers under some routers, that i wanna they share a cluster. For any large size of servers under a router, I'll specify a isolated etcd for them.

**Comment by fasaxc** [comment]
Why do you need separate Calico instances for each router?  Why can't you use a single Calico instance across all the routers?

If you use separate Calico instances, then Calico won't be able to "see" the workloads attached to other instances so you won't be able to use security rules that reference tags and labels.

**Comment by depay** [comment]
we do not use tag or other advanced profile currently, just allowing all the inbound or inbound to specific port, so that all-in-one is not that suitable for us...and i'm afraid bgp between routers is not so effective, that i prefer arranging different sub-net to routers with static routing..

**Comment by depay** [comment]
i would be allowed to deploy an all-in-one calico network by my net admins sometime, maybe..it sounds awesome..

**Comment by fasaxc** [comment]
So, is the issue that Calico generally assigns IPs at random whereas you need Calico to respect your existing static routes?  I.e. "if workload is in rack X then allocate IPs from pool Y".

What orchestrator are you using (Docker/k8s/Mesos/etc)?

**Comment by depay** [comment]
I’m using mesos only with docker container.

**Comment by ozdanborne** [comment]
@depay Is this one connected mesos cluster across s1-s6? Or is it two isolated clusters, where s1-s3 is connected to one master, and s4-s6 is another master? 

And can you confirm that fasaxc's point is the root issue here - that you need to assign IPs dynamically from different pools depending on which rack the task is being launched on?

**Comment by depay** [comment]
@djosborne 

for the 1st:
it's not the key point whether s1-s6 are in one cluster or not. That's just a example for explaining isolation with the same etcd.

for the 2nd:
for question `why not using an all-in-one calico network`, fasaxc's point is partly the issue. Another requirement besides is that we do not wanna create bgp connect across real routers, because our nodes are distributed under many different routers, while net admins make lots of restriction.

of course the best solution is calico support the upper two requirements: different pool & no bgp across racks. and it supports advanced profile.

currently, i made a workaround that deploying isolated calico and docker cluster storage for mesos-slaves under each racks, while creating docker network with same name, e.g. my_calico, on each group, so that i can create task with same parameter `--net my_calico` without concerning about where the docker task launches.

Generally speaking, an app should not using root path directly, since it can hardly avoiding from path-conflicts with another app. Even other apps do not, docker cluster-storage may use the same etcd of calico very likely, which is a risk for calico, i think.

**Comment by fasaxc** [comment]
@depay Thanks for the clarification.  We always prefix our keys with `/calico/` so we don't use the root directory directly.

I'm just worried about the additional complexity of having lots of independent Calico's in one etcd.  It's bound to get confusing to manage and labels/tags/rules won't work as expected.  It seems like the right solution is for us to support more refined IPAM within a single cluster.

It's already the case that the BGP piece of Calico is modular and can be swapped out for, say, flannel.

**Comment by depay** [comment]
thanks @fasaxc  @djosborne , i'm looking forward for the fantastic IPAM. :smile:  And i will deploy different etcd clusters for each subnet currently..

**Comment by tomdee** [comment]
Closing as it looks like this issue has been resolved. Please reopen if I've got this wrong.
