### ISSUE TITLE
Libcalico doesn't respect endpoint "name" from etcd.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico#133]
https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/datastore_datatypes.py#L261

Looks like libcalico always assumes the endpoint host-side veth name is the `cali` prefix + endpoint ID, which is totally broken.

New CNI code uses the _container_ side veth as the endpoint ID, which means the "name" field gets written as "calieth0".

**Comment by caseydavenport** [comment]
@robbrockbank I think we need to fix this as part of the set of releases you're planning on doing this week.  I can write the code + test, but please hold off on any releases until this is updated.

**Comment by robbrockbank** [comment]
Fixed by #134.  Will be in next release of libcalico (should be today)
