### ISSUE TITLE
calicoctl uses the IP address for the cbr0 docker bridge 

### ISSUE THREAD

**Issue by tomdee** [projectcalico/libcalico#15]
The `calicoctl node` command attempts to detect the which IP it should use. Currently we ignore the docker0 bridge but otherwise just use the address on the first interface that we find.

Kubernetes docs, recommend using a docker bridge called cbr0 - calico won't ignore this interface and can end up using this address.

**Comment by caseydavenport** [comment]
cc @TrimBiggs

**Comment by caseydavenport** [comment]
Calico-docker [PR #462](https://github.com/projectcalico/calico-docker/pull/462) fixes this.

**Comment by caseydavenport** [comment]
Should be fixed in the latest calico-docker release: https://github.com/projectcalico/calico-docker/releases/tag/v0.6.0

**Comment by fasaxc** [comment]
Shouldn't we bail out if it's ambiguous? This is hard to diagnose when it
happens.

**Comment by caseydavenport** [comment]
Yep, that might be sensible.
