### ISSUE TITLE
ipv4 block pool without affinity host setting issue

### ISSUE THREAD

**Issue by rmrf** [projectcalico/libcalico#193]
Our system is kind of old 
```
calico_node-libnetwork:v0.8.0
calico_node:v0.20.0
```
There are some ipv4 block pool missing affinity setting
such as this 
```
/calico/ipam/v2/assignment/ipv4/block/172.20.0.0-26

# etcdctl get /calico/ipam/v2/assignment/ipv4/block/172.20.0.0-26
{"affinity": "", "strict_affinity": false, "allocations": [0, 0, 0, null, null, null, 0, null, null, null, null, null, null, 0, null, null, null, null, null, null, 0, null, null, null, null, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, 0, 0, null, null, null, null, 0, null, null, null, null, null, null, 0, null, null, null, null, null, null, 0, null, null, null, null], "unallocated": [34, 11, 32, 48, 57, 19, 47, 56, 26, 30, 3, 21, 16, 12, 8, 60, 14, 9, 18, 28, 15, 29, 42, 61, 55, 33, 54, 58, 49, 10, 44, 53, 63, 24, 4, 35, 41, 7, 22, 62, 31, 17, 46, 51, 5, 50, 23, 27, 43, 37, 36], "attributes": [{"handle_id": null, "secondary": {}}], "cidr": "172.20.0.0/26"}


```

And this is causing issue when allocating docker container inside this ip pool, 
bellow is the log from alico_node-libnetwork: 
```
...
    block = AllocationBlock.from_etcd_result(result)
  File "/usr/lib/python2.7/site-packages/pycalico/block.py", line 134, in from_etcd_result
    assert affinity[:5] == "host:"
AssertionError
....
```
Not sure if I can assign an affinity host (which already have a ipv4 pool) to this `/calico/ipam/v2/assignment/ipv4/block/172.20.0.0-26` for fixing, will that making chaos?

Thanks!

**Comment by caseydavenport** [comment]
@rmrf did you at any point delete an IP pool which contains that block?

And, does a key exist at `/calico/ipam/v2/host/<nodename>` for the block? You could try writing in the correct host affinity there in the form `host:<nodename>` it should at least get rid of the immediate error.

However, v0.20.0 is _really_ old and a lot of IPAM fixes have been made since then. I strongly recommend upgrading to a modern version of Calico.

**Comment by rmrf** [comment]
@caseydavenport we have hosts removed from cluster (docker swarm), which containing this IP pool, which causing this. 

And, there is no key exist at `/calico/ipam/v2/host/<nodename>` for this block (seems this block turn to orphan after host remove)

So am I ok to assign another `parent` host to this `orphan IP pool` with bellow 2 steps? 
 -  add new key for `/calico/ipam/v2/host/<new parent>/ipv4/block/<orphan IP pool>`
 - add this `new parent` as this `orphan IP pool` 's `host:<nodename> `

Will it making big chaos as time goes? (network operation like this is kind of making me nervous... though we have DEV env to play with this, but not sure will it goes well as time goes)
