### ISSUE TITLE
Incorrect calculation of length in block.py

### ISSUE THREAD

**Issue by plwhite** [projectcalico/libcalico#21]
There are a couple of bugs in block.py which seem to cancel each other out, but could be tidied up (because I found them very confusing looking at the code).

```
PREFIX_MASK = {4: (IPAddress("255.255.255.255") ^ (BLOCK_SIZE - 1)),
               6: (IPAddress("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff") ^
                   (BLOCK_SIZE - 1))}
```

Sticking to IP v4, and with BLOCK_SIZE of 8, that leaves you with a mask of `255.255.255.248`, when you really want `255.255.255.0`. `test_get_block_cidr` still works though - it converts `10.34.11.75` to `10.34.11.72/24` - which is equal to `10.34.11.0/24` as an IPNetwork, even though it probably isn't what you want.

This should be fixed so that the test compares against a string rather than comparing against an IPNetwork to ensure that you really are getting what you want.

**Comment by spikecurtis** [comment]
I believe you are mistaken.

```
BLOCK_SIZE_BITS = 8
...
BLOCK_SIZE = 2 ** BLOCK_SIZE_BITS
PREFIX_MASK = {4: (IPAddress("255.255.255.255") ^ (BLOCK_SIZE - 1)),
               6: (IPAddress("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff") ^
                   (BLOCK_SIZE - 1))}
```

Which is to say, `BLOCK_SIZE` is 256, and thus we compute the `PREFIX_MASK`s correctly.

**Comment by plwhite** [comment]
Doh. Yes, I somehow misread BLOCK_SIZE as BLOCK_SIZE_BITS, sorry.
