### ISSUE TITLE
Exception in netns.py

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico#22]
@lwr20 was rerunning our scale testing script today, the build pulled in a new revision of libcalico and we started getting this error.  He's going to retry with an older revision to confirm that it was a regression.

```
Traceback (most recent call last):
  File "./host-agent.py", line 354, in <module>
    main()
  File "./host-agent.py", line 337, in main
    start_job(job_id, sub_job)
  File "./host-agent.py", line 199, in start_job
    netns.move_veth_into_ns(pid, ep.temp_interface_name, interface)
  File "/usr/local/lib/python2.7/site-packages/pycalico/netns.py", line 118, in move_veth_into_ns
    with NamedNamespace(namespace) as ns:
  File "/usr/local/lib/python2.7/site-packages/pycalico/netns.py", line 227, in __init__
    self.ns_path = namespace.path
AttributeError: 'int' object has no attribute 'path'
```

**Comment by lwr20** [comment]
The older version works.  The version I used was:
git+https://github.com/projectcalico/libcalico.git@d5b7cf7dca5f072aa2d66628e78fcc8048eb7f38#egg=libcalico

**Comment by alexhersh** [comment]
Check #13 
Libcalico v0.1.3 introduced a backwards-incompatible change to how we define namespaces. Now, instead of deriving namespace from a pid integer, we use the full path to the namespace as a `Namespace` object.

**Comment by alexhersh** [comment]
There is, however, a version of `Namespace()` called `PidNamespace()` which generates a path based on an integer. Basically, wherever you pass in `pid` as a namespace argument, you can replace it with `PidNamespace(pid)`

**Comment by tomdee** [comment]
@fasaxc @lwr20 So it looks like you need to update your scale script. Sorry for not making this change clearer in the release note (though is was mentioned - https://github.com/projectcalico/libcalico/releases/tag/v0.1.3)

I'm going to close the issue, feel free to reopen if you still think there's a bug here.
