### ISSUE TITLE
IPAMClient.auto_assign_ips assigns network and broadcast IPs

### ISSUE THREAD

**Issue by insequent** [projectcalico/libcalico#26]
Is there currently a solution to auto_assign only routable IPs, or is that considered a requirement of the consumer of ipam.py?

**Comment by insequent** [comment]
Temporarily, I have a check to account for this in my code:

```
    for num, ip in enumerate(v4_list):
        pool = client.get_pool(ip).cidr
        if ip in (pool.network, pool.broadcast):
            result = client.auto_assign_ips(1, 0, None, {}, 
                                            pool=(IPPool(pool), None))
            v4_list[num] = result[0][0]
```

**Comment by spikecurtis** [comment]
@insequent In Calico, all traffic is routed by the compute host.  There are no L2 broadcast domains and IP address pools are _not_ subnets.  Therefore, all addresses in the pool are routable.

Are you using Calico IPAM for something else that does include L2 broadcast domains?

**Comment by insequent** [comment]
@spikecurtis: That make sense, and no we're not doing anything with the broadcast. The pools we're assigning are slices of our rfc1918 network and typically those are subnets of physical boxes, but you're right, this is a different case here. Thanks for getting my head out of L2 land.
