### ISSUE TITLE
Rule objects don't validate parameters

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico#37]
When creating a libcalico rule, a minimal amount of validation is performed.  It would be significantly easier to debug policy problems if the given arguments (src_net, dst_tag, etc) were validated before being programmed to etcd so that errors in policy could be detected before being picked up by Felix.

**Comment by spikecurtis** [comment]
@caseydavenport can you elaborate on what validation you'd like to see?

**Comment by caseydavenport** [comment]
Sure.

There is already some validation - we check that `src_net` and `dst_net` can be cast as IPNetworks, and that the given actions is one of `allow` or `deny`.

I'd like to see validation of the `protocol` field - asserting that one of `["tcp", "udp", "icmp", None]` is provided (we've hit issues before when "TCP" was provided instead of "tcp" and felix barfed).

We should be validating that the `src_tag` and `dst_tag` do not contain any invalid characters that will cause them to be rejected by Felix.

We should be validating the given src/dst ports to ensure they are integers and within the valid port range.

We should validate that the `icmp_code` and `icmp_type` are valid values for those fields (e.g. 0 <= icmp_type <= 255).

**Comment by spikecurtis** [comment]
I like it.  All these are straightforward and immediately actionable.

**Comment by robbrockbank** [comment]
Fixed by #53
