### ISSUE TITLE
IPs allocated from a stale block when a pool is deleted

### ISSUE THREAD

**Issue by Symmetric** [projectcalico/libcalico#56]
Scenario:

Node configured with default calico pool. 
A container is created on the node, causing a block to be allocated to the host.
The default pool is deleted, and a new pool is added.
Another container is created on the node.

Result: the container is allocated an IP from the initially allocated block, instead of the pool that is currently configured.

Expected: the container gets an IP from the new pool. It's fine if the existing containers keep the IPs from the stale block.

**Comment by robbrockbank** [comment]
At the moment the IP Pool is used in the BIRD configuration to determine which routes should be exported.  This means that it is not fine if the existing containers keep the IPs from the stale block.  We probably need to do something to prevent a pool from being deleted if there are any IPs assigned from it.

**Comment by caseydavenport** [comment]
@robbrockbank We may want to prevent deleting pools if IPs are still assigned within it, but we also need to make sure that when the pool is deleted, so are any block assignments from that pool, right?

**Comment by robbrockbank** [comment]
Yes - so we probably want a flag in the IP Pool to ensure IPAM ignores it.  In fact we have something similar for libnetwork - so that libnetwork auto-assigned IPPools (created when using default docker IPAM) are not used when assigning IPs using our IPAM.

**Comment by robbrockbank** [comment]
Maybe we should have an enable/disable option on the IP pool, and make it that you can't delete it while there are IP addresses assigned.

**Comment by robbrockbank** [comment]
This has been fixed in calicoctl and libcalico.  Should be available in the next release.
