### ISSUE TITLE
The hostname argument for auto_assign_ips is not respected

### ISSUE THREAD

**Issue by plwhite** [projectcalico/libcalico#57]
When you call `auto_assign_ips`,  there is an optional `hostname` argument (defaulting to the hostname of this server). In principle, that means that you can have a name for a server used in IPAM that is not the same as the server hostname. Unfortunately, if you don't set it to the hostname of this server, then it doesn't work, which makes it a bit pointless.

The underlying issue is that `_auto_assign_block` is called, and that raises an exception if the block in question does not match the server hostname (not the `hostname` parameter). One fix would be to remove that check, but that seems a bit crazy (it's a valid check). Another fix would be to pass the supplied hostname down to `_auto_assign_block`, which I think is probably the correct fix.

I can probably put together a PR for this, but it'd be good to get confirmation that you agree with my analysis in case I've misunderstood how to use the interface.

Here's a stack trace of what happened when I tried this (`dummy-0000` is the hostname of the box, not what I passed, and this is build 0.3.0) : 

```
Traceback (most recent call last):
  File "./host-agent.py", line 532, in <module>
    main()
  File "./host-agent.py", line 374, in main
    do_ipam(name)
  File "./host-agent.py", line 342, in do_ipam
    hostname=name)
  File "/usr/local/lib/python2.7/site-packages/pycalico/ipam.py", line 409, in auto_assign_ips   
    attributes, pool[0], hostname)
  File "/usr/local/lib/python2.7/site-packages/pycalico/ipam.py", line 484, in _auto_assign
    attributes)
  File "/usr/local/lib/python2.7/site-packages/pycalico/ipam.py", line 538, in _auto_assign_block
    affinity_check=affinity_check)
  File "/usr/local/lib/python2.7/site-packages/pycalico/block.py", line 169, in auto_assign
    self.host_affinity)
pycalico.block.NoHostAffinityWarning: Host affinity is dummy-0000
```

**Comment by robbrockbank** [comment]
@plwhite 
Yup - looks like the correct fix is to plumb through the hostname.  Feel free to assign a PR to me if you get a fix out for this.

**Comment by spikecurtis** [comment]
@robbrockbank, @tomdee and I discussed this at length and our conclusion was to use the environment variable exclusively, rather than as a parameter on the function call.  If we're changing this again, I'd like us to reach a consistent position across the entire `libcalico` API.

**Comment by robbrockbank** [comment]
Ah @spikecurtis apologies.  What's the motivation for having the hostname passed in the IPAM API, but then not at the lower level in block.py?

**Comment by robbrockbank** [comment]
Actually @spikecurtis - I get your point, I assume Peter should just be setting the environment variable before using the API.

That said, the IPAM module does allow you to pass in a hostname - so this feels like a valid issue and solution to that use case, no?

**Comment by spikecurtis** [comment]
The original idea was to remove the hostname params on the IPAM API calls.  This got missed in the patch that added support for the environment variable.

**Comment by plwhite** [comment]
I am unhappy about using the HOSTNAME environment variable. There are two issues.
- You are passing parameters around in environment variables. It just feels completely odd to me that my python code has to set an environment variable to pass a parameter into libcalico.
- The HOSTNAME environment variable is a dangerous thing to set, and having to change it from, well, the hostname, might break other things. You might be assuming that the box hostname is the same as the name that it should use for IPAM, but there are counter-examples (rack based IPAM, OpenStack where the IPAM is done on the controller not the host, test environments and so on).

I would suggest that the IPAMClient object should : 
- Default to using the HOSTNAME environment variable, but have a "set_affinity_name" method or similar so it can be set any way you like (or maybe just leave it on the **init** method).
- Make the host_affinity check in the block object test against an optional supplied parameter.

I've had so many issues trying to get this working in my test code that I'm going to just fork and use my own fix until we get this sorted out, I think.

**Comment by spikecurtis** [comment]
@tomdee how do you feel about an optional constructor param for IPAMClient?

**Comment by fasaxc** [comment]
Using an environment variable seems wrong to me.  There's no reason I should have to run the IPAM allocation functions from the same host that I want to assign an IP for.  If we switch to libcalico in OpenStack, for example, we'd be assigning IPs from the centralised controller, not from the host that happens to be running the workload.

Defaulting to the local hostname belongs in the calicoctl layer IMHO.

**Comment by robbrockbank** [comment]
@spikecurtis FWIW, I don't think having it as constructor parameter is the right thing to do.

Firstly, moving it to the constructor suggests that you'd want to remove if from the IPAM API methods - which is a non-backwards compatible change which we generally try to avoid.

Secondly, I don't really feel that the IPAM client is host specific anymore than it is handle specific, say.  And, as Peter mentioned, I can imagine a situation where a single server would want to assign for multiple hosts - so making it forcing it to be hostname or ENV doesn't feel right.  I'm happy that, by default we use hostname or ENV if no hostname is supplied on the API,

Regarding the comment about consistent position with the rest of libcalico - most of the API does require hostname being passed in with the exception of IPAM (which we are discussing) and the ensure_global_config() method which actually might be more useful to add an optional hostname parm to.

**Comment by plwhite** [comment]
I don't mind whether it is a constructor or passed around - whatever works best for you guys.

However, there's a terminology thing here. If it's called "hostname", that implies that it's the hostname, which is clearly not always true. I'd prefer something more neutral such as "affinity_id", which might be the hostname of the server running the command, the hostname or ID of the hosting server, or the rack ID for the server running the command. Of course, that might imply breaking backwards compatibility which is a bad thing, but we'll generate confusion by having hostname parameters on multiple methods called "hostname", some of which are the hostname and some of which aren't.

**Comment by tomdee** [comment]
I agree with Peter, we've got the terminology wrong here. As part of fixing this up, we should be removing the bad references to "hostname" or "host" from ipam.py and replacing with affinity_id or whatever.

I don't feel too strongly about whether we
1) Change init of IPAMClient to allow an optional affinity_id (default to current hostname)
2) Add an extra method to IPAMClient to set the affinity_id (default to current hostname)
3) Update auto_assign_ips and assign_ip to take a affinity_id (in place of the current hostname parameter - but default to current hostname)

1) and 2) mean that a new IPAMClient object is required for each affinity_id but I don't think that's too big a deal.

(Whatever we do, we should sort out the parameters to auto_assign_ips and assign_ip and make everything else use the correct affinity_id and not fetch the "hostname" themselves)

**Comment by robbrockbank** [comment]
I personally prefer (3),  I think having an IPAM client per affinity ID doesn't play that nicely if you have a central point for IP assignment - you'd need a client per affinity ID (and therefore multiple etcd connections when it's not really necessary).  But it's not a strong preference.

Given this is a non-backwards compatible change, we could add the affinity_id alongside the hostname parameter.  Deprecate the hostname parm and remove it sometime later.  Or just just take the hit and update all the repos at the same time.  Any opinions?

**Comment by robbrockbank** [comment]
Actually, the data keys in etcd are "host" specific which is a pain.  If we want to change this properly we should update the keys too - so basically everything will break for existing deployments that have been using Calico IPAM.  Not so good.

**Comment by plwhite** [comment]
The data keys are tied to the host to which the block belongs, not the host that grabbed it (as you know, but I want to get my thoughts straight!). Obviously, that's wrong if we start saying that the affinity_id can be the rack (say), but it's not terrible to have data under `/calico/ipam/v2/host/<rack ID>`.

**Comment by robbrockbank** [comment]
Yup that's correct Peter.

I've discussed with @tomdee.  I'm intending to fix up as per option (3) - but the naming used in the etcd keys and values with still say "host" even though it's really the affinity_id.

**Comment by spikecurtis** [comment]
The intent was to allow multiple types of affinity, like host, rack, row, cluster, etc to be eventually added.  So I'd prefer to keep things concrete as "host" for now, rather than abstract "affinity_id".

Spike

Sent from Outlookhttp://aka.ms/Ox5hz3

On Thu, Dec 3, 2015 at 11:23 AM -0800, "robbrockbank" <notifications@github.com<mailto:notifications@github.com>> wrote:

Yup that's correct Peter.

I've discussed with @tomdeehttps://github.com/tomdee. I'm intending to fix up as per option (3) - but the naming used in the etcd keys and values with still say "host" even though it's really the affinity_id.

##

**Comment by plwhite** [comment]
OK - do you have an ETA for this? No hard deadline, but I've got workarounds in place and it would be quite nice to be able to clean them up. Thanks

**Comment by robbrockbank** [comment]
@plwhite 

This change has gone in.  After chatting with Spike and Tom we decided not to name affinity_id as a future development will be to add other affinity levels (such as rack).  That's a much bigger change, so for now we've just renamed hostname to be host so that it can represent a host ID of your choosing.  You can of course "abuse" the interface to be rack ID if that's what you require, but the default will be to use the hostname if no host parameter is supplied.

We should have a new release of this out by the end of the week, but current master has this change.
