### ISSUE TITLE
Improve perf by removing quorum reads

### ISSUE THREAD

**Issue by spikecurtis** [projectcalico/libcalico#60]
`libcalico` currently uses quorum reads on IPAM interactions.

Quorum reads are slower because they require interaction with a quorum of nodes.  We could improve perf by instead, tracking the index of every successful or failed write, and having our reads be >= that index.  Since the datastore object can be made stateful, we can do this without changing the `libcalico` API.

**Comment by fasaxc** [comment]
Not sure etcd has the concept of a quorum read; it does have consistent reads, which go via the master but we should profile and make sure those are an issue before we fix.

Closing for now, @matthewdupre please shout if you disagree.
