### ISSUE TITLE
IPAM fail when `masquerade` is set to `true`

### ISSUE THREAD

**Issue by tonicmuroq** [projectcalico/libcalico#68]
I use `calicoctl pool add 10.200.0.0/16 --nat-outgoing` to create pool, then I use `calicoctl container add 3e 10.200.0.0/16 --interface veth0.1` to add network from pool to container `3e`, it failed.

Error was: `ValueError: Requested pool 10.200.0.0/16 is not configured or haswrong attributes`.

But if I remove `"masquerade": true` in etcd, it works. And after this I add `"masquerade": true` back to etcd, it still works.

I run calico-node in docker with the latest version released about 2 days ago, calicoctl v0.13.0.

**Comment by tonicmuroq** [comment]
I found the problem and committed a [PR](https://github.com/projectcalico/calico-containers/pull/705). Another solution is that we only compare `cidr` of each `IPPool` and ignore `masquerade`, `ipip` and `ipam`.

**Comment by spikecurtis** [comment]
@tonicbupt Where did you submit the PR?  (to `calico-docker` repo?)  Can you link to it?

**Comment by tonicmuroq** [comment]
@spikecurtis  don't know why GitHub treat my PR link as issue link... [here](https://github.com/projectcalico/calico-containers/pull/705) is the PR to calico-docker, thanks
