### ISSUE TITLE
IP allocation of first address can be quite slow on a large system

### ISSUE THREAD

**Issue by plwhite** [projectcalico/libcalico#72]
When you grab the first address that has ever been used on a host, it scans through all of the known blocks checking to see if they are in use and attempting to grab them. Unfortunately, that can be quite slow on a large system. The example I have in front of me checked 1284 blocks taking 74 seconds before it found an unused one (though this is not a particularly fast server, and there was contention both for etcd and for CPU on the host itself, so I can believe this is uncharacteristic).

Two possible solutions came to mind.
- Do not scan through them in a fixed order, so that you are not guaranteed to hit all the used blocks before the unused ones. This is cheap and easy, but would actually break some of my test code, and doesn't feel like a long term solution.
- Have some kind of unused blocks list (that cannot be trusted and must be checked) to give you a hint which blocks are in use.

There is no significant impact on this issue on me in practice; I can grab enough blocks at start of day to avoid the issue. I reckon this might need to be fixed, but not at high priority.

**Comment by spikecurtis** [comment]
@plwhite do you know if the etcd v3 API contains a "list subkeys" operation (like list directory, but v3 API doesn't have directories) that is fast?  If we had that it would dramatically speed claiming a new, unused block.

**Comment by matthewdupre** [comment]
This should have been fixed by @gunjan5 (at least in libcalico-go): the search order is now random.
