### ISSUE TITLE
Allow specification of tags when creating new profile

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico#73]
Similar to how rules are implemented, so we don't have to perform multiple libcalico calls to configure a profile with tags.

```
def create_profile(self, name, rules=None):
```

becomes

```
def create_profile(self, name, rules=None, tags=None):
```

**Comment by robbrockbank** [comment]
Closing this issue as we should be migrating over to use libcalico-go (which does support this.... and tags are being deprecated)
